---
region: eu-west-2
delay_seconds: 120
metrics:
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_2XX_Count
  aws_dimensions: [TargetGroup, LoadBalancer]
  aws_dimension_select_regex:
    LoadBalancer:
      - 'app/.*-ingress.*'
  aws_statistics: [Sum]
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_3XX_Count
  aws_dimensions: [TargetGroup, LoadBalancer]
  aws_dimension_select_regex:
    LoadBalancer:
      - 'app/.*-ingress.*'
  aws_statistics: [Sum]
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_4XX_Count
  aws_dimensions: [TargetGroup, LoadBalancer]
  aws_dimension_select_regex:
    LoadBalancer:
      - 'app/.*-ingress.*'
  aws_statistics: [Sum]
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: HTTPCode_Target_5XX_Count
  aws_dimensions: [TargetGroup, LoadBalancer]
  aws_dimension_select_regex:
    LoadBalancer:
      - 'app/.*-ingress.*'
  aws_statistics: [Sum]
- aws_namespace: AWS/ApplicationELB
  aws_metric_name: TargetConnectionErrorCount
  aws_dimensions: [TargetGroup, LoadBalancer]
  aws_dimension_select_regex:
    LoadBalancer:
      - 'app/.*-ingress.*'
  aws_statistics: [Sum]
- aws_namespace: AWS/ECS
  aws_metric_name: CPUUtilization
  aws_dimensions: [ServiceName, ClusterName]
  aws_dimension_select:
    ServiceName:
      - prod-frontend
    ClusterName:
      - prod
  aws_statistics: [Average]
